/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    products: Product;
    categories: Category;
    services: Service;
    orders: Order;
    media: Media;
    posts: Post;
    'page-views': PageView;
    'analytics-summary': AnalyticsSummary;
    'api-keys': ApiKey;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    'analytics-summary': AnalyticsSummarySelect<false> | AnalyticsSummarySelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'sitemap-settings': SitemapSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'sitemap-settings': SitemapSettingsSelect<false> | SitemapSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  meta?: {
    /**
     * Defaults to page title if empty
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  layout?:
    | (
        | {
            /**
             * Main headline displayed over the hero image
             */
            heading: string;
            /**
             * Smaller text below the heading
             */
            subheading?: string | null;
            /**
             * Full-width background image (recommended: 1920x800+)
             */
            backgroundImage: number | Media;
            /**
             * Optional call-to-action button
             */
            ctaButton?: {
              label?: string | null;
              link?: string | null;
            };
            /**
             * Dark overlay opacity (0 = none, 100 = fully dark)
             */
            overlayOpacity?: number | null;
            textAlignment?: ('left' | 'center' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Formatted text — use the toolbar for headings, bold, italic, links, and lists
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Maximum width of the text content area
             */
            maxWidth?: ('narrow' | 'medium' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Section heading above the product grid
             */
            heading?: string | null;
            /**
             * Choose specific products or auto-fill from a category
             */
            populateMode?: ('manual' | 'auto') | null;
            /**
             * Select the products to display
             */
            products?: (number | Product)[] | null;
            /**
             * Products from this category will be shown
             */
            category?: (number | null) | Category;
            /**
             * Maximum number of products to display
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProducts';
          }
        | {
            /**
             * Section heading above the services grid
             */
            heading?: string | null;
            /**
             * Choose specific services or auto-fill
             */
            populateMode?: ('manual' | 'auto') | null;
            /**
             * Select the services to display
             */
            services?: (number | Service)[] | null;
            /**
             * Maximum number of services to display
             */
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredServices';
          }
        | {
            /**
             * Image displayed alongside the text content
             */
            image: number | Media;
            /**
             * Text content displayed next to the image
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Which side the image appears on
             */
            layout?: ('image-left' | 'image-right') | null;
            /**
             * Optional background color (hex or CSS color)
             */
            backgroundColor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            /**
             * Section heading above the testimonials
             */
            heading?: string | null;
            /**
             * Add customer testimonials — each with a quote, author name, and optional photo
             */
            items?:
              | {
                  title?: string | null;
                  quote: string;
                  author: string;
                  /**
                   * e.g., "Tandem Flight Customer"
                   */
                  role?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            /**
             * Bold heading text for the banner
             */
            heading: string;
            /**
             * Supporting text below the heading (plain text only — use Code Embed for HTML)
             */
            text?: string | null;
            /**
             * Button text (e.g., "Book Now", "Learn More")
             */
            buttonLabel: string;
            /**
             * URL the button links to (e.g., /contact)
             */
            buttonLink: string;
            /**
             * Optional background image (overrides background color)
             */
            backgroundImage?: (number | null) | Media;
            /**
             * Fallback background color if no image (e.g., #1B3C2D)
             */
            backgroundColor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            /**
             * Section heading above the FAQ list
             */
            heading?: string | null;
            /**
             * Add questions and answers — each item expands/collapses on the page
             */
            items?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqAccordion';
          }
        | {
            /**
             * Optional heading above the gallery grid
             */
            heading?: string | null;
            /**
             * Upload images — each can have an optional caption
             */
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Number of columns in the gallery grid
             */
            columns?: ('2' | '3' | '4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            /**
             * Amount of vertical space to add between blocks
             */
            height: 'small' | 'medium' | 'large';
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
        | {
            /**
             * Internal label for this embed (not shown on the page, just for your reference)
             */
            label?: string | null;
            /**
             * Paste HTML, iframes, or script tags here. This code renders directly on the frontend. Use this block for booking widgets, embedded forms, maps, etc.
             */
            code: string;
            /**
             * Maximum width of the embed container
             */
            maxWidth?: ('narrow' | 'medium' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'codeEmbed';
          }
      )[]
    | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Price in USD
   */
  price: number;
  /**
   * Original price for showing discounts
   */
  compareAtPrice?: number | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Add available sizes for this product
   */
  sizes?:
    | {
        /**
         * Display label (e.g. "XS", "Small")
         */
        label: string;
        /**
         * Internal value (e.g. "xs", "s")
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Add available color options for this product
   */
  colors?:
    | {
        /**
         * Display label (e.g. "HTA/W", "Custom")
         */
        label: string;
        /**
         * Internal value (e.g. "hta-w", "custom")
         */
        value: string;
        /**
         * Override price for this color. Leave blank to use default product price.
         */
        priceModifier?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional sizing chart (tables, text, etc.)
   */
  sizingChart?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  /**
   * Brand / manufacturer name (e.g. "Ozone", "Gin", "SUP'Air")
   */
  manufacturer?: string | null;
  /**
   * EN certification class
   */
  enRating?: ('EN A' | 'EN B' | 'EN C' | 'EN D' | 'CCC') | null;
  sku?: string | null;
  inventory?: number | null;
  status: 'active' | 'archived';
  meta?: {
    /**
     * Defaults to product name if empty
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO
     */
    metaKeywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Price in USD. Leave empty if using contact for pricing.
   */
  price?: number | null;
  /**
   * Show "Contact for pricing" instead of a price
   */
  contactForPricing?: boolean | null;
  image?: (number | null) | Media;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Button label for this service
   */
  ctaLabel?: string | null;
  /**
   * URL the button links to (external booking, etc.)
   */
  ctaLink?: string | null;
  status: 'active' | 'archived';
  meta?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items: {
    product?: (number | null) | Product;
    service?: (number | null) | Service;
    name: string;
    price: number;
    quantity: number;
    id?: string | null;
  }[];
  total: number;
  /**
   * Square payment ID
   */
  paymentId: string;
  customerEmail: string;
  customerName?: string | null;
  status: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  /**
   * Short summary shown on the blog listing page
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  /**
   * Author name displayed on the post
   */
  author?: string | null;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  meta?: {
    /**
     * Defaults to post title if empty
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: number;
  path: string;
  /**
   * SHA-256 hash of IP + User-Agent (privacy-safe unique visitor ID)
   */
  visitorHash: string;
  referrer?: string | null;
  userAgent?: string | null;
  device?: ('desktop' | 'mobile' | 'tablet') | null;
  /**
   * Date portion (YYYY-MM-DD) for daily rollup queries
   */
  sessionDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-summary".
 */
export interface AnalyticsSummary {
  id: number;
  date: string;
  path: string;
  views: number;
  uniqueVisitors: number;
  topReferrers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  deviceBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  label: string;
  keyHash: string;
  keyPrefix: string;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'page-views';
        value: number | PageView;
      } | null)
    | ({
        relationTo: 'analytics-summary';
        value: number | AnalyticsSummary;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              ctaButton?:
                | T
                | {
                    label?: T;
                    link?: T;
                  };
              overlayOpacity?: T;
              textAlignment?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              maxWidth?: T;
              id?: T;
              blockName?: T;
            };
        featuredProducts?:
          | T
          | {
              heading?: T;
              populateMode?: T;
              products?: T;
              category?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        featuredServices?:
          | T
          | {
              heading?: T;
              populateMode?: T;
              services?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              image?: T;
              content?: T;
              layout?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              heading?: T;
              text?: T;
              buttonLabel?: T;
              buttonLink?: T;
              backgroundImage?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        faqAccordion?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              height?: T;
              id?: T;
              blockName?: T;
            };
        codeEmbed?:
          | T
          | {
              label?: T;
              code?: T;
              maxWidth?: T;
              id?: T;
              blockName?: T;
            };
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  compareAtPrice?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  sizes?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  colors?:
    | T
    | {
        label?: T;
        value?: T;
        priceModifier?: T;
        id?: T;
      };
  sizingChart?: T;
  category?: T;
  manufacturer?: T;
  enRating?: T;
  sku?: T;
  inventory?: T;
  status?: T;
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  contactForPricing?: T;
  image?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaLink?: T;
  status?: T;
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        service?: T;
        name?: T;
        price?: T;
        quantity?: T;
        id?: T;
      };
  total?: T;
  paymentId?: T;
  customerEmail?: T;
  customerName?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  publishedAt?: T;
  status?: T;
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  path?: T;
  visitorHash?: T;
  referrer?: T;
  userAgent?: T;
  device?: T;
  sessionDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-summary_select".
 */
export interface AnalyticsSummarySelect<T extends boolean = true> {
  date?: T;
  path?: T;
  views?: T;
  uniqueVisitors?: T;
  topReferrers?: T;
  deviceBreakdown?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  label?: T;
  keyHash?: T;
  keyPrefix?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  header?: {
    logo?: (number | null) | Media;
    logoText?: string | null;
    /**
     * Logo size as a percentage of the default (100 = original, 90 = 10% smaller). Adjust in increments of 5.
     */
    logoScale?: number | null;
    navLinks?:
      | {
          label: string;
          linkType?: ('page' | 'url' | 'product' | 'category') | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: number | Category;
              } | null);
          url?: string | null;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    ctaButton?: {
      label?: string | null;
      link?: string | null;
      style?: ('primary' | 'outline') | null;
    };
  };
  footer?: {
    columns?:
      | {
          heading: string;
          links?:
            | {
                label: string;
                url: string;
                openInNewTab?: boolean | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    copyrightText?: string | null;
    socialLinks?:
      | {
          platform: 'facebook' | 'twitter' | 'instagram' | 'pinterest' | 'youtube' | 'tiktok' | 'yelp';
          url: string;
          id?: string | null;
        }[]
      | null;
    bottomLinks?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Select which page to display as the homepage
   */
  homepage?: (number | null) | Page;
  brandColors?: {
    /**
     * Primary brand color (forest green)
     */
    primary?: string | null;
    /**
     * Secondary brand color (amber)
     */
    secondary?: string | null;
    /**
     * Accent color (cream)
     */
    accent?: string | null;
  };
  seo?: {
    siteName?: string | null;
    titleSuffix?: string | null;
    defaultDescription?: string | null;
    defaultOgImage?: (number | null) | Media;
  };
  newsletter?: {
    heading?: string | null;
    description?: string | null;
    enabled?: boolean | null;
  };
  /**
   * Configure Square payment processing. Enter your Square credentials to enable checkout on the storefront.
   */
  payments?: {
    /**
     * When disabled, the checkout button will be hidden and customers cannot make purchases.
     */
    paymentsEnabled?: boolean | null;
    /**
     * Use Sandbox for testing with test cards. Switch to Production when ready to accept real payments.
     */
    squareEnvironment?: ('sandbox' | 'production') | null;
    /**
     * Found in your Square Developer Dashboard under your application credentials.
     */
    squareAppId?: string | null;
    /**
     * The location ID for the Square business location to process payments against.
     */
    squareLocationId?: string | null;
    /**
     * Your Square access token. This is sensitive — keep it secret. Used server-side only; never exposed to the browser.
     */
    squareAccessToken?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the automatically generated XML sitemap that is published at /sitemap.xml.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitemap-settings".
 */
export interface SitemapSetting {
  id: number;
  /**
   * When disabled, the site will stop advertising the sitemap in robots.txt and return an empty sitemap response.
   */
  enabled?: boolean | null;
  /**
   * These routes are included before dynamic content. Use site-relative paths such as /contact or /blog.
   */
  staticEntries?:
    | {
        /**
         * Site-relative path or full URL. Full URLs will be normalized back to a path.
         */
        path: string;
        changeFrequency: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
        /**
         * Priority from 0.0 to 1.0.
         */
        priority: number;
        id?: string | null;
      }[]
    | null;
  dynamicCollections?: {
    pages?: boolean | null;
    posts?: boolean | null;
    products?: boolean | null;
    services?: boolean | null;
    categories?: boolean | null;
  };
  /**
   * Optional. Enter one site-relative path per line to remove it from the generated sitemap, including dynamic URLs.
   */
  excludePaths?: string | null;
  /**
   * Controls how often the server cron should regenerate sitemap.xml and robots.txt from the saved settings.
   */
  generationFrequency?: ('manual' | 'hourly' | 'daily' | 'weekly' | 'monthly') | null;
  lastGeneratedAt?: string | null;
  lastGeneratedCount?: number | null;
  lastGenerationStatus?: ('success' | 'failed') | null;
  lastGenerationMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  header?:
    | T
    | {
        logo?: T;
        logoText?: T;
        logoScale?: T;
        navLinks?:
          | T
          | {
              label?: T;
              linkType?: T;
              reference?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        ctaButton?:
          | T
          | {
              label?: T;
              link?: T;
              style?: T;
            };
      };
  footer?:
    | T
    | {
        columns?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
            };
        copyrightText?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        bottomLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
      };
  homepage?: T;
  brandColors?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
      };
  seo?:
    | T
    | {
        siteName?: T;
        titleSuffix?: T;
        defaultDescription?: T;
        defaultOgImage?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        description?: T;
        enabled?: T;
      };
  payments?:
    | T
    | {
        paymentsEnabled?: T;
        squareEnvironment?: T;
        squareAppId?: T;
        squareLocationId?: T;
        squareAccessToken?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitemap-settings_select".
 */
export interface SitemapSettingsSelect<T extends boolean = true> {
  enabled?: T;
  staticEntries?:
    | T
    | {
        path?: T;
        changeFrequency?: T;
        priority?: T;
        id?: T;
      };
  dynamicCollections?:
    | T
    | {
        pages?: T;
        posts?: T;
        products?: T;
        services?: T;
        categories?: T;
      };
  excludePaths?: T;
  generationFrequency?: T;
  lastGeneratedAt?: T;
  lastGeneratedCount?: T;
  lastGenerationStatus?: T;
  lastGenerationMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}